### ISSUE TITLE
Death will also cause the skin not to refresh Can it be fixed through this mod?

### ISSUE THREAD

**Issue by zChenX1** [NLR-DevTeam/SkinPartsRefresher#1]
Player Death will also cause the skin not to refresh Can it be fixed through this mod?

**Comment by XIAYM-gh** [comment]
wait what
I added this feature in mod version 1.0.1, didn't it work correctly?

**Comment by XIAYM-gh** [comment]
oh well
I tested again and can't reproduce the bug
(/suicide in overworld, it refreshed 1 time because of respawning, it worked correctly)
(/suicide in world_the_end, it refreshed 2 times because of respawning and dimension changing, and it worked correctly)
can u tell me how to reproduce the bug?

**Comment by zChenX1** [comment]
> well maybe is my question thank you

**Comment by zChenX1** [comment]
> 哦，好吧，我再次测试了，无法重现该错误（/在主世界中自杀，由于重生，它刷新了 1 次，它工作正常）（/自杀在 world_the_end，由于重生和维度变化，它刷新了 2 次，并且工作正常）你能告诉我如何重现这个错误吗？

测试了一会 大概明白了 自动重生（/gamerule doImmediateRespawn true）的时候模组的皮肤刷新不会生效xwx

**Comment by XIAYM-gh** [comment]
?怪
mc java版啥时候加的这游戏规则 这段要了
不过我这个模组用的是ClientTickStart Event, 这个游戏规则可能会让玩家在死亡tick就重生，让它不能正常检测
我回去试试改成WorldTickStart Event (
try try 按N手动刷新

**Comment by XIAYM-gh** [comment]
改成WorldTickStart Event之后可以了
Submiting to github & modrinth (

**Comment by zChenX1** [comment]
> ?怪 mc java版啥时候加的这游戏规则 这段要了 不过我这个模组用的是ClientTickStart Event, 这个游戏规则可能会让玩家在死亡tick就重生，让它不能正常检测 我回去试试改成WorldTickStart Event ( try try 按N手动刷新

1.15加的（

**Comment by zChenX1** [comment]
> 改成WorldTickStart Event之后可以了 Submiting to github & modrinth (

好快（喜

**Comment by XIAYM-gh** [comment]
我快 但是gradle不快 一个reload task跑了十分钟 恼
